
platform :ios, '9.0'

use_frameworks!

target 'SwiftAlert_Example' do
	
	pod 'SwiftAlert', :path => '../'

  target 'SwiftAlert_ExampleTests' do
    inherit! :search_paths
    pod 'SwiftAlert', :path => '../'
    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
  
#  target 'ExampleUITests' do
#    inherit! :search_paths
#    pod 'SwiftAlert', :path => '../'
#    pod 'Quick'
#    pod 'Nimble'
#    pod 'FBSnapshotTestCase'
#    pod 'Nimble-Snapshots'
#  end
end
