use_frameworks!

target 'Alert_Example' do
  pod 'Alert', :path => '../'

  target 'Alert_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
